#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export CONTEXT_ENV="${0##*/}"
  exec "$@"
}

source sub "$BASH_SOURCE" "$@"
